name: pointage
description: application de pointage et géolocalisation.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  barcode_scan:
  qr_flutter:
  path_provider:
  flutter_vector_icons:
  animations: ^2.0.0
  geolocator: ^6.1.9 
  image_picker: 
  convex_bottom_bar: ^3.0.0
  url_launcher: ^6.0.3
  google_fonts: ^0.3.5
  flutter_appauth: ^0.9.1
  flutter_secure_storage: ^3.3.3
  http:
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^9.0.0
  google_ml_kit: ^0.5.0
  tflite_flutter: ^0.8.0
  camera: ^0.8.1
  image: ^3.0.2
  flutter_slidable: ^0.6.0
  animated_text_kit: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "images/luncher.png"
  ios: true
  android: true

flutter:

  uses-material-design: true
  assets:
     - images/logo.png
     - images/facebook.png
     - images/instagram.png
     - images/linkedin.png
     - images/luncher.png
     - images/feedbackImage.png
